### ISSUE TITLE
node v9

### ISSUE THREAD

**Issue by RobinRadic** [MarkGriffiths/trucolor#118]
Currently node v9 is not supported. Any plans on this?

As workaround i currently have:

**.yarnrc**
```
--add.ignore-engines true
--install.ignore-engines true
```

**package.json**
```json
{
    "postinstall": "node _fix-bespoke.js"
}
```

**_fix-bespoke.js**
```js
const fs = require('fs')
const path = require('path')
const globule = require('globule')

let packages = [
    '@thebespokepixel/es-tinycolor',
    '@thebespokepixel/meta',
    '@thebespokepixel/n-selector',
    '@thebespokepixel/string',
    '@thebespokepixel/time',
    'trucolor',
    'truwrap',
    'verbosity',
    'sgr-composer',
    'term-ng'
]


packages.forEach(name => {
    console.log('packesgs')
    let paths = globule.find(path.resolve('node_modules', name, '**/*', 'index-v8.js'));
    paths.forEach(path => {
        if(!fs.existsSync(path)) {
            return;
        }
        let destPath = path.replace('v8', 'v9');
        if(!fs.existsSync(destPath)) {
            console.log({path,destPath})
            fs.writeFileSync(destPath, fs.readFileSync(path, 'utf-8'), 'utf-8');
        }

    })
})
```

**Comment by MarkGriffiths** [comment]
Apologies... my update plans got stalled behind a bug in npm 5 which blocked me from updating my shared workflow @thebespokepixel/cordial tool and I've been stuck in node 7 at work :/

I'll endeavour to give all my repos some attention over the coming week - it's well overdue.

**Comment by MarkGriffiths** [comment]
Only taken me 4 months to find the time to fix everything, but all is finally back up to date and updated for the current ecosystem… thanks for the input and apologies it's taken so long!

**Comment by RobinRadic** [comment]
Better late then never.
Thanks!
