### ISSUE TITLE
How do i using output background when using trucolor programmaticly 

### ISSUE THREAD

**Issue by RobinRadic** [MarkGriffiths/trucolor#69]
For example:
```javascript
function getColor(color){
  return trucolor.bulk({ output: 'sgr|value|swatch' }, { color: color }).color
}
// works fine
var c= getColor('red')
console.log(c.in + ' this is red text ' + c.out);

// does not work, the text is red instead of the background
var bc = getColor('background red')
console.log(bc.in + ' this is red bg ' + bc.out);
```

How can i color backgrounds?  Been searching trough the code but i haven't been able to do this

**Comment by MarkGriffiths** [comment]
Firstly, could you try the following from your root package directory:

```js
./node_modules/.bin/trucolor -m ' Background ' background red
```

If that produces a coloured background ok, then all is fine with your terminal configuration.

I'd then try then following:

```js
function getColor(color){
  return trucolor.bulk({}, { color: color }).color
}
// works fine
var c= getColor('red')
console.log(c.in + ' this is red text ' + c.out);

// does not work, the text is red instead of the background
var bc = getColor('background red')
console.log(bc.in + ' this is red bg ' + bc.out);
```

The bulk function will default to `sgr` when no `output` configuration is supplied. Let me know how that goes. The module is due some attention but I'm still a bit buried in other supporting modules before I can give it some needed polish. Should be in the next few days! (famous last words)

**Comment by RobinRadic** [comment]
My issue was terminal configuration fail, i was sure it was configured properly...
Thanks a lot!
